# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{qips-node-amqp}
  s.version = "0.7.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Austin", "Andrew Brader"]
  s.date = %q{2010-10-05}
  s.description = %q{Listens for jobs on a rabbit server, works closely with qipr-rmgr}
  s.email = %q{daustin@mail.med.upenn.edu}
  s.executables = ["qips-node-amqp", "status-updater.rb"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "bin/qips-node-amqp",
     "bin/status-updater.rb",
     "config/amqp.yml",
     "config/arguments.rb",
     "config/aws.rb.sample",
     "config/boot.rb",
     "config/environment.rb",
     "config/environments/development.rb",
     "config/environments/production.rb",
     "config/environments/test.rb",
     "config/initializers/qips-node-amqp.rb",
     "config/post-daemonize/readme",
     "config/pre-daemonize/readme",
     "config/ruote.yml",
     "lib/ilims_helper.rb",
     "lib/item.rb",
     "lib/project.rb",
     "lib/qips-node-amqp.rb",
     "lib/s3_helper.rb",
     "lib/status_writer.rb",
     "lib/work_item_helper.rb",
     "lib/worker.rb",
     "libexec/qips-node-amqp-daemon.rb",
     "pills/qips-node.pill",
     "pkg/qips-node-amqp-0.0.0.gem",
     "pkg/qips-node-amqp-0.1.0.gem",
     "pkg/qips-node-amqp-0.2.0.gem",
     "pkg/qips-node-amqp-0.2.1.gem",
     "pkg/qips-node-amqp-0.2.2.gem",
     "pkg/qips-node-amqp-0.2.3.gem",
     "pkg/qips-node-amqp-0.2.4.gem",
     "pkg/qips-node-amqp-0.3.0.gem",
     "pkg/qips-node-amqp-0.3.1.gem",
     "pkg/qips-node-amqp-0.3.2.gem",
     "pkg/qips-node-amqp-0.4.0.gem",
     "pkg/qips-node-amqp-0.4.1.gem",
     "pkg/qips-node-amqp-0.4.2.gem",
     "pkg/qips-node-amqp-0.4.3.gem",
     "pkg/qips-node-amqp-0.4.4.gem",
     "pkg/qips-node-amqp-0.4.5.gem",
     "pkg/qips-node-amqp-0.5.0.gem",
     "qips-node-amqp.gemspec",
     "script/console",
     "script/destroy",
     "script/generate",
     "spec/qips-node-amqp_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/rspec.rake"
  ]
  s.homepage = %q{http://github.com/daustin/qips-node-amqp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{AMQP worker node for QIPS suite}
  s.test_files = [
    "spec/qips-node-amqp_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<right_aws>, [">= 1.10.0"])
      s.add_runtime_dependency(%q<activesupport>, ["= 2.3.5"])
      s.add_runtime_dependency(%q<activeresource>, ["= 2.3.5"])
      s.add_runtime_dependency(%q<ruote>, ["= 2.1.7"])
      s.add_runtime_dependency(%q<json>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<amqp>, ["= 0.6.7"])
      s.add_runtime_dependency(%q<daemon-kit>, ["= 0.1.8pre"])
      s.add_runtime_dependency(%q<rest-client>, ["= 1.5.1"])
      s.add_runtime_dependency(%q<mzml>, [">= 0.1.0"])
    else
      s.add_dependency(%q<right_aws>, [">= 1.10.0"])
      s.add_dependency(%q<activesupport>, ["= 2.3.5"])
      s.add_dependency(%q<activeresource>, ["= 2.3.5"])
      s.add_dependency(%q<ruote>, ["= 2.1.7"])
      s.add_dependency(%q<json>, [">= 1.2.0"])
      s.add_dependency(%q<amqp>, ["= 0.6.7"])
      s.add_dependency(%q<daemon-kit>, ["= 0.1.8pre"])
      s.add_dependency(%q<rest-client>, ["= 1.5.1"])
      s.add_dependency(%q<mzml>, [">= 0.1.0"])
    end
  else
    s.add_dependency(%q<right_aws>, [">= 1.10.0"])
    s.add_dependency(%q<activesupport>, ["= 2.3.5"])
    s.add_dependency(%q<activeresource>, ["= 2.3.5"])
    s.add_dependency(%q<ruote>, ["= 2.1.7"])
    s.add_dependency(%q<json>, [">= 1.2.0"])
    s.add_dependency(%q<amqp>, ["= 0.6.7"])
    s.add_dependency(%q<daemon-kit>, ["= 0.1.8pre"])
    s.add_dependency(%q<rest-client>, ["= 1.5.1"])
    s.add_dependency(%q<mzml>, [">= 0.1.0"])
  end
end

